## Modeling

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from datetime import datetime
from datetime import timedelta

from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import roc_auc_score

%matplotlib inline

In [3]:
train_csv = "../Emma/train_weather_per_station.csv"
train=pd.read_csv(train_csv)

test_csv = "../Emma/test_weather_per_station.csv"
test=pd.read_csv(test_csv)

In [4]:
pd.set_option("display.max_columns",50)

In [5]:
train.head()

,Date,Num_Duplicates,WnvPresent,Year,Month,Day,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Cool,Sunrise,Sunset,PrecipTotal,ResultSpeed,ResultDir
0,2007-05-29,1,0,2007,5,29,0,0,1,0,0,0,0,88,60,74,10,58,65,9,421,1917,0.0,5.8,18
1,2007-05-29,1,0,2007,5,29,0,0,0,1,0,0,0,88,60,74,10,58,65,9,421,1917,0.0,5.8,18
2,2007-05-29,1,0,2007,5,29,0,0,0,1,0,0,0,88,60,74,10,58,65,9,421,1917,0.0,5.8,18
3,2007-05-29,1,0,2007,5,29,0,0,1,0,0,0,0,88,60,74,10,58,65,9,421,1917,0.0,5.8,18
4,2007-05-29,1,0,2007,5,29,0,0,0,1,0,0,0,88,60,74,10,58,65,9,421,1917,0.0,5.8,18

## Setting up the data for modeling

In [6]:
# creating polynomial interactions of just the weather features

pf = PolynomialFeatures(include_bias=False)
weather_features = ["Tmax", "Tmin", "Tavg", "Depart", "DewPoint", "WetBulb", "Cool", "Sunrise", "Sunset",
                   "PrecipTotal", "ResultSpeed", "ResultDir"]
polyed_weather = pf.fit_transform(train[weather_features])
polyweather_df = pd.DataFrame(polyed_weather, columns=pf.get_feature_names(weather_features))
polyweather_df.drop(labels=weather_features, axis=1, inplace=True)

In [7]:
train["UNSPECIFIED CULEX"] = 0

In [8]:
train = train.join(polyweather_df)

In [9]:
print(train.shape)
train.head()

(10506, 104)

,Date,Num_Duplicates,WnvPresent,Year,Month,Day,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Cool,Sunrise,Sunset,PrecipTotal,ResultSpeed,ResultDir,...,WetBulb Sunset,WetBulb PrecipTotal,WetBulb ResultSpeed,WetBulb ResultDir,Cool^2,Cool Sunrise,Cool Sunset,Cool PrecipTotal,Cool ResultSpeed,Cool ResultDir,Sunrise^2,Sunrise Sunset,Sunrise PrecipTotal,Sunrise ResultSpeed,Sunrise ResultDir,Sunset^2,Sunset PrecipTotal,Sunset ResultSpeed,Sunset ResultDir,PrecipTotal^2,PrecipTotal ResultSpeed,PrecipTotal ResultDir,ResultSpeed^2,ResultSpeed ResultDir,ResultDir^2
0,2007-05-29,1,0,2007,5,29,0,0,1,0,0,0,0,88,60,74,10,58,65,9,421,1917,0.0,5.8,18,...,124605.0,0.0,377.0,1170.0,81.0,3789.0,17253.0,0.0,52.2,162.0,177241.0,807057.0,0.0,2441.8,7578.0,3674889.0,0.0,11118.6,34506.0,0.0,0.0,0.0,33.64,104.4,324.0
1,2007-05-29,1,0,2007,5,29,0,0,0,1,0,0,0,88,60,74,10,58,65,9,421,1917,0.0,5.8,18,...,124605.0,0.0,377.0,1170.0,81.0,3789.0,17253.0,0.0,52.2,162.0,177241.0,807057.0,0.0,2441.8,7578.0,3674889.0,0.0,11118.6,34506.0,0.0,0.0,0.0,33.64,104.4,324.0
2,2007-05-29,1,0,2007,5,29,0,0,0,1,0,0,0,88,60,74,10,58,65,9,421,1917,0.0,5.8,18,...,124605.0,0.0,377.0,1170.0,81.0,3789.0,17253.0,0.0,52.2,162.0,177241.0,807057.0,0.0,2441.8,7578.0,3674889.0,0.0,11118.6,34506.0,0.0,0.0,0.0,33.64,104.4,324.0
3,2007-05-29,1,0,2007,5,29,0,0,1,0,0,0,0,88,60,74,10,58,65,9,421,1917,0.0,5.8,18,...,124605.0,0.0,377.0,1170.0,81.0,3789.0,17253.0,0.0,52.2,162.0,177241.0,807057.0,0.0,2441.8,7578.0,3674889.0,0.0,11118.6,34506.0,0.0,0.0,0.0,33.64,104.4,324.0
4,2007-05-29,1,0,2007,5,29,0,0,0,1,0,0,0,88,60,74,10,58,65,9,421,1917,0.0,5.8,18,...,124605.0,0.0,377.0,1170.0,81.0,3789.0,17253.0,0.0,52.2,162.0,177241.0,807057.0,0.0,2441.8,7578.0,3674889.0,0.0,11118.6,34506.0,0.0,0.0,0.0,33.64,104.4,324.0

In [10]:
# date is redundant with year/month/day columns and unreadable by some classifiers
train.drop(labels="Date", axis=1, inplace=True)

In [11]:
print((train[train.WnvPresent==1]).count()["WnvPresent"])
print((train[train.WnvPresent==0]).count()["WnvPresent"])

1218
9288

In [12]:
# data is very imbalanced so bootstrapping to evenness
wnv_pres = train[train.WnvPresent==1]
train_bootstrapped = wnv_pres.sample(n=8000, replace=True)

In [13]:
train = pd.merge(train, train_bootstrapped, how="outer")

## Feature selection and modeling

In [14]:
features = [x for x in train.columns if x != "WnvPresent"]
y = train.WnvPresent
X = train[features]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

### Models with pipeline

In [16]:
ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

In [26]:
models  = {'rf': [RandomForestClassifier(random_state = 1), {'n_estimators' : [20, 30],
                                                'max_depth' : [30, 40]}],
         'et': [ExtraTreesClassifier(random_state = 1), {'n_estimators' : [40, 50],
                                                'max_depth' : [30, 40]}],
         'bag': [BaggingClassifier(random_state = 1), {'n_estimators' : [10, 15]}],
              'ada': [AdaBoostClassifier(random_state = 1), {'n_estimators' : [70, 80]}],
              'knn': [KNeighborsClassifier(), {'n_neighbors': [3]}],
              'lg': [LogisticRegressionCV(random_state = 1), {'Cs': [1, 10, 15]}],
            }

In [27]:
for k, v in models.items():
    gs = GridSearchCV(v[0], v[1])
    gs.fit(X_train_scaled, y_train)
    y_pred = gs.predict(X_test_scaled)
    print(k, gs.best_params_, roc_auc_score(y_test, y_pred))

rf {'max_depth': 30, 'n_estimators': 30} 0.9133163047393803
et {'max_depth': 30, 'n_estimators': 50} 0.916659634328551
bag {'n_estimators': 15} 0.9110920440848561
ada {'n_estimators': 80} 0.8536646182701968
knn {'n_neighbors': 3} 0.9089836802130373
lg {'Cs': 15} 0.821799645241848

## Working with the hold out set

In [28]:
test.shape

(116293, 25)

In [29]:
poly_test = pf.transform(test[weather_features])
polytest_df = pd.DataFrame(poly_test, columns=pf.get_feature_names(weather_features))

In [30]:
test.drop(labels=weather_features, axis=1, inplace=True)
test = test.join(polytest_df)

In [31]:
test.drop(labels="Date", axis=1, inplace=True)

In [33]:
test_scaled = ss.transform(test)

et = ExtraTreesClassifier(n_estimators = 50, max_depth = 30)
et.fit(X_train_scaled, y_train)
et_preds = et.predict(test_scaled)
et_preds_df = pd.DataFrame(data=et_preds, columns=["WnvPresent"])
et_preds_df.index.rename("Id", inplace=True)
et_preds_df.index += 1
et_preds_df.to_csv("./extra_trees_preds")